# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Availee-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Koyomi'
  # Pods for Availee-iOS

  target 'Availee-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Availee-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
